name: 每30分钟更新直播源
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install requests
        run: pip install requests

      - name: Run crawl
        run: python crawl.py

      - name: Push files
        run: |
          git config user.name "ActionsBot"
          git config user.email "bot@github.com"
          git add live.txt live.m3u
          git commit -m "Auto update live files"
          git push
